config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
      resources :glows
  end

  get '/glows'=>"home#index"
  get 'dashboard/reports', as: 'reports'
  get 'dashboard/all_report', as: 'all_report'
  get 'dashboard/other_report', as: 'other_report'
  root 'welcome#index'

end

app/models/glow.rb
require 'csv'
class Glow < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :quote
  paginates_per 10


def self.to_csv
    CSV.generate do |csv|
      csv << Glow.new.attributes.keys
      Glow.all.each do |glow|
        csv << glow.attributes.values
      end
    end
  end
end

app/models/user.rb
require 'csv'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :glows
  validates_presence_of :username, :first_name, :last_name
  validates_uniqueness_of :username

  has_attached_file :avatar,
  :styles => { :medium => "300x300>", :thumb => "100x100>" },
  :bucket => 'kbjsinstaclone',
  :url =>':s3_domain_url',
  :path => ':class/:attachment/:id_partition/:style/:filename',
  :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.to_csv
    CSV.generate do |csv|
      csv << User.new.attributes.keys
      User.all.each do |user|
        csv << user.attributes.values
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name, :username, :avatar)
  end

#   def after_sign_in_path_for(resource)
#   session["user_return_to"] || posts_show_path
#   end

#   def after_sign_up_path_for(resource)
#     session["user_return_to"] || posts_show_path
#   end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @title = "Positivity | Dashboard"
    @users = User.all
  end

  def reports
  end

  def all_report
    respond_to do |format|
      format.csv do
        render text: User.to_csv
      end
    end
  end

  def other_report
    respond_to do |format|
      format.csv do
        render text: Glow.to_csv
      end
    end
  end

end

app/controllers/glows_controller.rb
class GlowsController < ApplicationController
  before_action :authenticate_user!

def index
    @user = User.all
    @glows = Glow.all
  end

  def new
    set_user
    set_new_glow
  end

  def create
      @glow = Glow.new(glow_params)
      user = current_user
      @glow.user_id = user.id
      respond_to do |format|
        if @glow.save
          format.html { redirect_to users_path, notice: 'Glow was successfully created.' }
          format.json { render :show, status: :created, location: @glow }

        else
          format.html { render :new }
          format.json { render json: @glow.errors, status: :unprocessable_entity }
        end
      end
  end


  private
    def set_glow
      @glow = Glow.find(params[:id])
    end
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_new_glow
      @new_glow = Glow.new
    end

    def glow_params
    params.require(:glow).permit(:user_id, :quote, :subject, :author)
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :avatar)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  # @user = User.first
  @glows = Glow.all.page params[:page]
  @users = User.all
  # user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!

def index
  @user = current_user
  @glows = Glow.all
end

def new
  @user = User.new
  @glow = Glow.new
end

def create
  @user = User.new(user_params)

  respond_to do |format|
    if @user.save
      format.html { redirect_to @user, notice: 'User was successfully created.' }
      format.json { render json: @user, status: :created, location: @user }
    else
      format.html { render "welcome/index" }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
  end


  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  @user = User.first
  @glows = Glow.all
  @users = User.all
  user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/glows_helper.rb
module GlowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/reports.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <div class="well well-lg">
        <h2 style="text-align: center">Reports</h2>
      </div>
      <ul class="list-group">
        <li class="list-group-item">
          <%= link_to "Users Report (as CSV)", all_report_path('csv') %>
        </li>
        <li class="list-group-item">
          <%= link_to "Glows Report (as CSV)", other_report_path('csv') %>
        </li>
      </ul>
    </div>
    <div class="col-md-3">
    </div>
  </div>
</div>

app/views/glows/index.html.erb
<h1>glows index</h1>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <div class="well well-lg">
        <h2 style="text-align: center">Look on the bright side!  </h2>
      </div>
      <h3> Glows</h3><br />
      <% @glows.each do |glow| %>
        <blockquote>
          <p>"<%= glow.quote %>"</p>
          <small><cite title="Source Title">by: <%= glow.author %> </cite></small>
          <small><%= glow.subject %></small>
          <small>Posted by <%= glow.user.username %></small>
          </blockquote>
          <% end %>
        <%= paginate @glows %><br />
        <%= page_entries_info @glows %>
      </div>
    </div>
    <div class="col-md-3">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "Positivity | Glow" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.2/journal/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" >Positivity!</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
       <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Home', root_path %><span class="sr-only">(current)</span></a></li>
        <% if user_signed_in? %>
        <li class="active"><%= link_to 'All Glows', glows_path %><span class="sr-only">(current)</span></a></li>
        <li class="active"><%= link_to 'My Glows', users_path %><span class="sr-only">(current)</span></a></li>
        <li class="active"><%= link_to('Logout', destroy_user_session_path(@current_user), :method => :delete) %><span class="sr-only">(current)</span></a></li>

        <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to "Reports", reports_path %><span class="sr-only">(current)</span></a></li>
      </ul>
    </div>
  </div>
</nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<%= simple_form_for([current_user, Glow.new], multipart: true) do |f| %>
<%= f.error_notification %>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="well well-lg">
        <h3 style="text-align: center">Let your light shine! What glow do you have for the world?</h3>
      </div>
      <div class="form-inputs">
        <%= f.input :subject %>
        <%= f.input :quote, required: true %>
        <%= f.input :author %>
      </div>
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
      <% end %>
    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-6">
      <div class="well well-lg">
        <h2 style="text-align: center">Look on the bright side!  </h2>
      </div>

      <span class="avatar-image"><%= image_tag current_user.avatar.url(:thumb) %></span>
      <h3 class="avatar-name"> <%= @user.username.capitalize %>'s Glows</h3><br />
      <% @user.glows.each do |glow| %>
      <div class='block'>
        <blockquote>
          <p>"<%= glow.quote %>"</p>
          <small><cite title="Source Title">by: <%= glow.author %> </cite></small>
          <small><%= glow.subject %></small>
        </blockquote>
      <% end %>
    </div>
    <div class="col-md-1">
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Positivity</h1>

    <% if user_signed_in? %>

        <p><%= link_to('Logout', destroy_user_session_path(@current_user), :method => :delete, class: "btn btn-primary btn-lg" ) %></p>
        <p><%= link_to('Take me to my Glows', users_path, class: "btn btn-primary btn-lg")%></p>
        <p><%= link_to('Take me to all Glows', glows_path, class: "btn btn-primary btn-lg") %></p>
      <% else %>
        <p><%= link_to('Sign Up Now', new_user_registration_path, class: "btn btn-primary btn-lg")%></p>
        <p><%= link_to('Sign In Now', new_user_session_path, class: "btn btn-primary btn-lg")%></p>

      <% end %>

  </div>
</div>